CREATE VIEW [dbo].[VW_NEXT_ACTIVITY_FISCAL_YEARS]
	AS
  SELECT compkey, [1] AS next_inspection_fy, [2] AS next_root_fy, [3] AS next_cleaning_fy
FROM (SELECT COMPKEY, ACTIVITY_TYPE_ID, NEXTACTIVI FROM VW_NEXT_ACTIVITIES_BY_COMPKEY) PS
PIVOT (MIN(NEXTACTIVI) FOR ACTIVITY_TYPE_ID IN ([1], [2], [3])) AS PVT