CREATE TABLE [dbo].[REHAB10FTSEGS] (
    [OBJECTID]                INT             NOT NULL,
    [mlinkid]                 INT             NULL,
    [compkey]                 INT             NULL,
    [usnode]                  NVARCHAR (6)    NULL,
    [dsnode]                  NVARCHAR (6)    NULL,
    [linktype]                NVARCHAR (2)    NULL,
    [flowtype]                NVARCHAR (2)    NULL,
    [length]                  NUMERIC (38, 8) NULL,
    [diamwidth]               NUMERIC (8, 2)  NULL,
    [height]                  NUMERIC (8, 2)  NULL,
    [pipeshape]               NVARCHAR (255)  NULL,
    [material]                NVARCHAR (10)   NULL,
    [instdate]                DATETIME        NULL,
    [hservstat]               NVARCHAR (255)  NULL,
    [bsnrun]                  NVARCHAR (5)    NULL,
    [old_mlid]                INT             NULL,
    [cutno]                   INT             NULL,
    [fm]                      NUMERIC (8, 2)  NULL,
    [to_]                     NUMERIC (8, 2)  NULL,
    [seglen]                  NUMERIC (8, 2)  NULL,
    [grade_h5]                SMALLINT        NULL,
    [mat_fmto]                NVARCHAR (21)   NULL,
    [seg_count]               SMALLINT        NULL,
    [fail_near]               INT             NULL,
    [fail_prev]               INT             NULL,
    [fail_tot]                INT             NULL,
    [fail_pct]                NUMERIC (8, 2)  NULL,
    [def_pts]                 INT             NULL,
    [def_lin]                 INT             NULL,
    [def_tot]                 INT             NULL,
    [bpw]                     INT             NULL,
    [apw]                     INT             NULL,
    [cbr]                     NUMERIC (38, 8) NULL,
    [insp_date]               DATETIME        NULL,
    [insp_yrsago]             SMALLINT        NULL,
    [insp_curr]               SMALLINT        NULL,
    [fail_yr]                 SMALLINT        NULL,
    [rulife]                  SMALLINT        NULL,
    [rul_flag]                SMALLINT        NULL,
    [std_dev]                 INT             NULL,
    [cof]                     INT             NULL,
    [replacecost]             INT             NULL,
    [action]                  SMALLINT        NULL,
    [remarks]                 NVARCHAR (100)  NULL,
    [bpw_seg]                 INT             NULL,
    [apw_seg]                 INT             NULL,
    [cbr_seg]                 NUMERIC (38, 8) NULL,
    [std_dev_seg]             INT             NULL,
    [fail_yr_seg]             SMALLINT        NULL,
    [fail_yr_whole]           SMALLINT        NULL,
    [std_dev_whole]           SMALLINT        NULL,
    [Exceptions]              NVARCHAR (1000) NULL,
    [ACCUM_RISK_REPLACE_YEAR] SMALLINT        NULL,
    [ACCUM_RISK_INSPECT_YEAR] SMALLINT        NULL,
    [SHAPE]                   INT             NULL,
    [CBR_RANK]                INT             NULL,
    [CBRSEG_RANK]             INT             NULL,
    [BPW_RANK]                INT             NULL,
    [BPWSEG_RANK]             INT             NULL,
    [asset_set_id]            INT             NULL
);

