CREATE PROCEDURE [dbo].[SP_CREATE_NUMS]
	@maxNum bigint = 1000000
AS
BEGIN
  IF OBJECT_ID('dbo.NUMS') IS NOT NULL DROP TABLE dbo.NUMS;
  CREATE TABLE dbo.NUMS (n BIGINT NOT NULL PRIMARY KEY);

  DECLARE @rc AS BIGINT
  SET @rc = 1;

  INSERT INTO NUMS VALUES(1);
  WHILE @rc*2 <= @maxNum
  BEGIN
    INSERT INTO NUMS SELECT n + @rc FROM NUMS
    SET @rc = @rc * 2
  END

  INSERT INTO NUMS
  SELECT n + @rc FROM NUMS WHERE n + @rc <= @maxNum
END