-- =============================================
-- Author: Arnel Mandilag
-- Create date: 5/30/2012
-- Description:	Initializes database for base case
-- =============================================
CREATE PROCEDURE [dbo].[SP_INIT_DB]
AS
BEGIN
  EXEC SP_STATUS_MESSAGE 'Begin SP_INIT_DB'

  -- Clean up Asset/Base Data
  TRUNCATE TABLE ASSETS
  TRUNCATE TABLE ASSETS_UPDATE
  TRUNCATE TABLE ASSET_SETS
  TRUNCATE TABLE LatestInspections
  TRUNCATE TABLE REHAB10FTSEGS
  TRUNCATE TABLE RootInspections
  TRUNCATE TABLE SpecialRoot
  TRUNCATE TABLE ALTERNATIVES

  -- Clean up Model Data
  TRUNCATE TABLE ACTIVITIES
  TRUNCATE TABLE CONTROLLING_DRIVER_FREQUENCIES
  TRUNCATE TABLE DRIVERS
  TRUNCATE TABLE DRIVERS_UPDATE
  TRUNCATE TABLE NEXT_ACTIVITIES

  -- Clean up Lookups
  TRUNCATE TABLE ACCELERATED_CLEANING_CAUSE_TYPES
  TRUNCATE TABLE ALTERNATIVES
  TRUNCATE TABLE BASIN_TYPES
  TRUNCATE TABLE BASINS
  TRUNCATE TABLE DISTRICTS
  TRUNCATE TABLE DRIVER_TYPES
  TRUNCATE TABLE TRACTIVE_FORCE_GRADES

  -- Set up first asset set
  SET IDENTITY_INSERT ASSET_SETS ON
  INSERT INTO ASSET_SETS ([asset_set_id], [name], [import_date], [description]) VALUES
    (1, 'Initial import', GETDATE(), NULL);
  SET IDENTITY_INSERT ASSET_SETS OFF

  -- Set up first "alternative" (base case)
  SET IDENTITY_INSERT ALTERNATIVES ON;
  INSERT INTO ALTERNATIVES ([alternative_id], [name], [description], [asset_set_id]) VALUES
    (1, 'Current', NULL, 1);
  SET IDENTITY_INSERT ALTERNATIVES OFF;

  EXEC SP_FILL_LOOKUPS

  EXEC SP_FILL_DRIVER_TYPES @alternative_id =1

  EXEC SP_STATUS_MESSAGE 'End SP_INIT_DB'
END